### PR TITLE
Implement QuickSort for rust

### LINKED ISSUE #135: Write a Rust programme for Quick sort
### Description

Write a programme for Quick sort

```
Input  : 5 4 1 6 2
Output : 1 2 4 5 6
```

### PR DESCRIPTION
**Pull request by Pablito2020**
### Why:

Closes #135 

### What's being changed:
Added an implementation of quicksort that uses generics and is easy to understand and read.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by PrajwalBorkar — CHANGES_REQUESTED** [review]
When I run this program, Im getting this error - 

> 

error: expected identifier, found keyword `crate`
  --> main.rs:33:9
   |
33 |     use crate::quicksort;
   |         ^^^^^

error: aborting due to previous error(s)

**Comment by PrajwalBorkar** [comment]
I'm not familiar with rust but I tried on multiple compilers same error is there. Please check if there is an error.

**Comment by Pablito2020** [comment]
Sorry, I was using [cargo](https://doc.rust-lang.org/cargo/) (the default package manager and tool for compiling packages in rust) and I used the test library that comes with it. Since in this repo only the rust file is needed (not the whole cargo project) it was not compiling. 

The solution that I added on commit 6d7326c3b002dd7f16d54c13724fa61131f5fe69 is to write the tests on main instead inside a different package. Now, with rustc, compiles fine.

**Comment by PrajwalBorkar** [comment]
Thanks for the changes. Also instead of a direct approach, you have implemented test cases so I think we will have to see what @harshraj8843 has to say about this.

**Comment by harshraj8843** [comment]
Hey @Pablito2020 

Could you please modify the code so that it can use test cases alongside with direct approach

Means test message will only be shown on `test fail`

**Comment by Pablito2020** [comment]
Done! Now the program only shows the message panicking when the result isn't the expected!

**Review by PrajwalBorkar — APPROVED** [review]

**Comment by PrajwalBorkar** [comment]
@harshraj8843 the README.md doesn't look good when more contributors are added, the description column gets smaller. Should we modify that?

**Comment by harshraj8843** [comment]
> Should we modify that?

Actually we can't

the purpose of adding contributors is to show contributors on website

Screenshot from 2022-08-03 23-57-43

**Comment by PrajwalBorkar** [comment]
Actually, I was wondering if we can add rows in contributor section instead of one single line because the description looks weird.

Screenshot (76)

**Comment by harshraj8843** [comment]
> Actually, I was wondering if we can add rows in contributor section instead of one single line because the description looks weird.

Any solution for this @PrajwalBorkar ?

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by PrajwalBorkar** [comment]
> > Actually, I was wondering if we can add rows in contributor section instead of one single line because the description looks weird.
> 
> Any solution for this @PrajwalBorkar ?

No, I don't know any. That's why I asked you.

**Comment by harshraj8843** [comment]
> No, I don't know any. That's why I asked you.

ok I will try ASAP 🤗

**Pull request merged**
