### PR TITLE
Paolofer new algorithm validate-palindrome

### LINKED ISSUE #35: Write a Python programme to validate palindrome
### Description

Write a programme to validate palindrome

```
Input  : radar
Output : True
```

### LINKED ISSUE #37: Write a JavaScript programme to validate palindrome
### Description

Write a programme to validate palindrome

```
Input  : radar
Output : True
```

### PR DESCRIPTION
**Pull request by PaoloFer**
### Why : 

Closes #35 
Closes #37 

### What's being changed:

- Add validate-palindrome directory
- Add Readme.me
- Add validate-palindrome.py
- Add validate-palindrome.js

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by PaoloFer** [comment]
Can someone review my pr so that i can do changes to fix the error that i've done

**Comment by PaoloFer** [comment]
Sorry for the formatting error, have you some advice to improve it?

**Comment by harshraj8843** [comment]
> Sorry for the formatting error, have you some advice to improve it?

You can use [python code formater](https://marketplace.visualstudio.com/items?itemName=ms-python.python) in VS Code

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by PaoloFer** [comment]
thanks for the advice

**Pull request merged**
