### PR TITLE
Selectionsort c

### LINKED ISSUE #82: Write a C programme for Selection sort
### Description

Write a programme for Selection sort

```
Input  : 5 4 1 6 2
Output : 1 2 4 5 6
```

### PR DESCRIPTION
**Pull request by harsh0c**
### Why:

Closes #82 

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by Ashad001 — COMMENTED** [review]
The header file includes all the libraries for c++ at once 
```
#include <bits/stdc++.h>
```
Whereas there is no any need of other header file except 
```
#include <iostream>
```
This will reduce the program size as well.
So my recommendation would be to remove the current and add the following header file.
```diff
-#include<bits/stdc++.h>
+#include<iostream>
```

**Comment by curious0207** [comment]
My bad I want only selection sort in C to be merged, the cpp file has already been merged what should I do?

**Comment by Ashad001** [comment]
I have requested the selection sort  in C. Can you please check it out?
[Selection Sort In C](https://github.com/codinasion/codinasion-dsa/pull/160)

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Pull request merged**
