### PR TITLE
implemented binary search in javascript. issue #26

### LINKED ISSUE #26: Write a JavaScript programme for binary search
### Description

Write a programme for binary search

```
Input  : 10 20 30 50 60 80
Target : 30

Output : 2
```

### PR DESCRIPTION
**Pull request by rashmod**
### Why:

Closes #26

### What's being changed:
Added a new file binary-search.js. Implemented binary search function.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by PrajwalBorkar — COMMENTED** [review]
Great Work 👍 , also updated the readme file.

**Comment by rashmod** [comment]
You should close the issue

**Comment by PrajwalBorkar** [comment]
No, I cant merge PR @harshraj8843  will do.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
